# setwd("C:/2025IBESMAIN/")
if(!require(sodium)) install.packages("sodium")
if(!require(base64enc)) install.packages("base64enc")
readRenviron("Renviron")

# Load required libraries
library(sodium)
library(base64enc)
Sys.getenv("k")
Sys.getenv("n")
Sys.getenv("TESTVARIABLEu_1")
Sys.getenv("TESTVARIABLEp_2")
Sys.getenv("TESTVARIABLEw_3")
Sys.getenv("TESTVARIABLEs_4")
k <- base64decode(Sys.getenv("k"))
n <- base64decode(Sys.getenv("n"))
w <- base64decode(Sys.getenv("TESTVARIABLEw_3"))
s <- base64decode(Sys.getenv("TESTVARIABLEs_4"))
us <- base64decode(Sys.getenv("TESTVARIABLEu_1"))
up <- base64decode(Sys.getenv("TESTVARIABLEp_2"))
Sys.setenv("new_sv"    =  rawToChar(data_decrypt(s, k, n)))
Sys.setenv("new_wp" =  rawToChar(data_decrypt(w, k, n)))
Sys.setenv("old_u"      =  rawToChar(data_decrypt(us, k, n)))
Sys.setenv("old_d"  =  rawToChar(data_decrypt(up, k, n)))

set_credentials(paste0("https://",Sys.getenv("new_sv")), Sys.getenv("new_wp"),Sys.getenv("old_u"),Sys.getenv("old_d"))
suso_set_key(paste0("https://",Sys.getenv("new_sv")),Sys.getenv("old_u"), Sys.getenv("old_d"))
